quartz:
  enabled: true
server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
    tomcat:
      initialSize: 20
      maxActive: 100
      maxIdle: 100
      minIdle: 20
      maxWait: 10000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
